[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_nft_anchor = "AG9ohc91DeVe1yRF2TymSLNK4PQfquzyBQWoyA81J2ed"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/almei/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
